config/routes.rb
Rails.application.routes.draw do
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
 
  root 'blog#index'

  get 'blog/index'

  get 'blog/posts'

  resources :posts
  resources :categories
  resources :authors
  

end

app/models/author.rb
class Author < ActiveRecord::Base
end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :category
  belongs_to :author
  mount_uploader :cover, CoverUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]

  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url, notice: 'Author was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:name, :email, :contact)
    end
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
  def index
  end

  def posts
  	@posts =  Post.all
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  layout 'blog'
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :description, :content, :category_id, :author_id, :cover)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/authors/_form.html.erb
<%= form_for(@author) do |f| %>
  <% if @author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
      <% @author.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :contact %><br>
    <%= f.text_field :contact %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<h1>Editing Author</h1>

<%= render 'form' %>

<%= link_to 'Show', @author %> |
<%= link_to 'Back', authors_path %>

app/views/authors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Authors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Contact</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @authors.each do |author| %>
      <tr>
        <td><%= author.name %></td>
        <td><%= author.email %></td>
        <td><%= author.contact %></td>
        <td><%= link_to 'Show', author %></td>
        <td><%= link_to 'Edit', edit_author_path(author) %></td>
        <td><%= link_to 'Destroy', author, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Author', new_author_path %>

app/views/authors/new.html.erb
<h1>New Author</h1>

<%= render 'form' %>

<%= link_to 'Back', authors_path %>

app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @author.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @author.email %>
</p>

<p>
  <strong>Contact:</strong>
  <%= @author.contact %>
</p>

<%= link_to 'Edit', edit_author_path(@author) %> |
<%= link_to 'Back', authors_path %>

app/views/blog/index.html.erb
		<!-- BEGIN ABOUT SECTION-->
		<section id="about" class="section section-bg-light section-top-rise section-bottom-rise">
			<div class="section-inner">

				<div class="container">

					<header class="heading">
						<h2>Quem Sou</h2>
						<div class="separator"></div>
					</header>

					<div class="row">
						<div class="col span_4 center">
							<div class="site-photo"><img src="images/neuly2.jpg" width="250" height="250" alt="Photo" class="photo"></div>
						</div>
						<div class="col span_8">
							<h3>Neuly Ferreira da Silva</h3>
							<p>Nascida em Rio Verde, fui criada em Coxim e etc...</p>
							
						</div>
					</div>

				</div>

			</div>
		</section>
		<!-- END ABOUT SECTION-->

		

	

	

		<!-- BEGIN PROJECTS SECTION-->
		<section id="projects" class="section">
			<div class="section-inner">

				<div class="container">

					<header class="heading">
						<h2>Meus Projetos</h2>
						<div class="separator"></div>
					</header>

					<ul class="filter">
						<li data-group="all" class="active">Todos</li>
						<li data-group="web">Gastronomia</li>
						<li data-group="illustration">Infantil</li>
						<li data-group="branding">Cultural</li>
					</ul>

					<ul class="works">
						<li data-groups="[&quot;web&quot;]" class="works-item"><a href="#works-item-details-1" class="works-item-link"><span class="works-item-thumb"><img src="images/work-thumb-1.jpg" width="250" height="250" alt=""></span></a>
							<div id="works-item-details-1" class="popup mfp-hide">
								<figure><img src="images/work-photo-1.jpg" width="750" height="500" alt=""></figure>
								<div class="popup-inner">
									<h3>Disk and Folder</h3>
									<p>Lorem ipsum dolor sit amet, bibendum justo fusce. Phasellus duis urna. Enim sollicitudin. Posuere arcu risus, leo faucibus massa, libero nunc orci. Cursus egestas nulla, neque libero lobortis, cursus adipiscing aliquam.</p>
									<div class="center"><a href="#" class="btn">View site</a></div>
								</div>
							</div>
						</li>
						<li data-groups="[&quot;branding&quot;]" class="works-item"><a href="#works-item-details-2" class="works-item-link"><span class="works-item-thumb"><img src="images/work-thumb-2.jpg" width="250" height="250" alt=""></span></a>
							<div id="works-item-details-2" class="popup mfp-hide">
								<figure><img src="images/work-photo-2.jpg" width="750" height="500" alt=""></figure>
								<div class="popup-inner">
									<h3>Label Brand</h3>
									<p>Lorem ipsum dolor sit amet, metus amet. Orci eleifend, mauris taciti. Vivamus ac. Convallis nam. Duis sodales, felis vel. In nam, viverra ac. Eget phasellus. Cras dictum at, fames lorem. Non integer cursus.</p>
									<div class="center"><a href="#" class="btn">View site</a></div>
								</div>
							</div>
						</li>
						<li data-groups="[&quot;web&quot;]" class="works-item works-item-w"><a href="#works-item-details-3" class="works-item-link"><span class="works-item-thumb"><img src="images/work-thumb-3.jpg" width="250" height="250" alt=""></span></a>
							<div id="works-item-details-3" class="popup mfp-hide">
								<figure><img src="images/work-photo-3.jpg" width="750" height="500" alt=""></figure>
								<div class="popup-inner">
									<h3>Label Brand</h3>
									<p>Lorem ipsum dolor sit amet, massa nunc nulla, vitae fusce. Diam elit, nulla habitasse iaculis. Condimentum cursus. Egestas duis. Ut et egestas, est non, ut sit.</p>
									<div class="center"><a href="#" class="btn">View site</a></div>
								</div>
							</div>
						</li>
						<li data-groups="[&quot;illustration&quot;]" class="works-item works-item-t"><a href="#works-item-details-4" class="works-item-link"><span class="works-item-thumb"><img src="images/work-thumb-4.jpg" width="250" height="250" alt=""></span></a>
							<div id="works-item-details-4" class="popup mfp-hide">
								<figure><img src="images/work-photo-4.jpg" width="750" height="500" alt=""></figure>
								<div class="popup-inner">
									<h3>Paper Bag Packaging</h3>
									<p>Lorem ipsum dolor sit amet, mauris diam. Magna eros. Sed eu, vitae et quis, nibh arcu. Id aliquam mollis. Tincidunt aliquam aliquam, wisi ornare.</p>
									<div class="center"><a href="#" class="btn">View site</a></div>
								</div>
							</div>
						</li>
						<li data-groups="[&quot;web&quot;]" class="works-item"><a href="#works-item-details-5" class="works-item-link"><span class="works-item-thumb"><img src="images/work-thumb-5.jpg" width="250" height="250" alt=""></span></a>
							<div id="works-item-details-5" class="popup mfp-hide">
								<figure><img src="images/work-photo-5.jpg" width="750" height="500" alt=""></figure>
								<div class="popup-inner">
									<h3>Retro Frame Presentation Poster</h3>
									<p>Lorem ipsum dolor sit amet, curabitur sed tellus, per ipsum vestibulum, mauris ipsum. Cursus morbi, tortor vel. Nec neque, neque non vitae, sit augue sociosqu. Scelerisque praesent, egestas suspendisse habitasse. Sit conubia, libero massa et, ut tempus lacinia. Velit nibh nam, justo sed, vestibulum rutrum aliquam. Erat sem congue.</p>
									<div class="center"><a href="#" class="btn">View site</a></div>
								</div>
							</div>
						</li>
						<li data-groups="[&quot;branding&quot;]" class="works-item"><a href="#works-item-details-6" class="works-item-link"><span class="works-item-thumb"><img src="images/work-thumb-6.jpg" width="250" height="250" alt=""></span></a>
							<div id="works-item-details-6" class="popup mfp-hide">
								<figure><img src="images/work-photo-6.jpg" width="750" height="500" alt=""></figure>
								<div class="popup-inner">
									<h3>Notepad Presentation</h3>
									<p>Lorem ipsum dolor sit amet, ultricies nulla quis, hendrerit sed. Vehicula egestas, vestibulum a. Hymenaeos ante ullamcorper, quam id. Sed ac, pretium erat ut. Elit tempor urna, sed mus.</p>
									<div class="center"><a href="#" class="btn">View site</a></div>
								</div>
							</div>
						</li>
					</ul>

				</div>

			</div>
		</section>
		<!-- END PROJECTS SECTION-->

app/views/blog/posts.html.erb
<section class="section">
			<div class="section-inner">

				<div class="container">

					<header class="heading">
						<h2>Blog</h2>
					</header>

					<div class="posts">
						<% @posts.each do |post| %>
						<article class="post">
							<div class="post-thumbnail"><img src="<%= post.cover %>" width="250" height="250" alt=""></div>
							<h3><%= link_to post.title, post %></h3>
							<div class="post-meta">
								<div class="date"><%= post.created_at.strftime('%d/%m/%Y') %></div>
							</div>
							<div class="post-meta">
								<div class="date"><%= post.category.name %></div>
							</div>
							<p><%= post.description %>...</p>
						</article>
						<% end %>
					</div>

					<ul class="pagination">
						<li class="active"><a href="#">1</a></li>
						<li><a href="#">2</a></li>
						<li><a href="#">3</a></li>
						<li><a href="#">4</a></li>
						<li><a href="#">5</a></li>
					</ul>
				</div>
			</div>
		</section>

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PapoDoDia</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/blog.html.erb
<!DOCTYPE html>
<!--[if lte IE 9]>
<html lang="en" class="lte-ie9">
<![endif]-->
<!--[if gt IE 9]><!-->
<html lang="pt">
<!--<![endif]-->

<head>

	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<title>Papo do Dia - com Neuly Ferreira </title>
	<meta name="description" content="One-page responsive VC HTML template">
	<meta name="keywords" content="template, clean, responsive, one-page, creative, vc">
	<meta name="author" content="Alex Ilin">

	<!-- Place favicon.ico in the root directory-->

	<!-- Animate.css-->
	<link rel="stylesheet" href="/styles/animate.min.css">

	<!-- Normalize CSS-->
	<link rel="stylesheet" href="/styles/normalize.css">

	<!-- Magnific Popup-->
	<link rel="stylesheet" href="/plugins/magnific-popup/magnific-popup.css">

	<!-- Owl carousel-->
	<link rel="stylesheet" href="/plugins/owl-carousel/owl.carousel.css">

	<!-- Font Awesome-->
	<link rel="stylesheet" href="/styles/font-awesome.min.css">

	<!-- Google Fonts-->
	<link href="http://fonts.googleapis.com/css?family=Roboto+Mono:400,400italic,700italic,700%7CNothing+You+Could+Do" rel="stylesheet">

	<link rel="stylesheet" href="/styles/main.css">

</head>

<body>

	<!-- BEGIN NAV-->
	<div class="main-nav">
		<nav>
			<ul>
				<li><%= link_to 'Inicio',root_path %></li>
				
				<li><%= link_to 'Blog', :controller => 'blog', :action => 'posts' %></li>
			</ul>
		</nav>
		<div class="btn-icon btn-nav">
			<div class="line"></div>
			<div class="line"></div>
			<div class="line"></div>
		</div>
	</div>
	<!-- END NAV-->

	<div class="wrapper h-card">

		<!-- BEGIN HEADER-->
		<section id="intro" class="section section-bg-img section-bg-overlay section-bottom-rise">
			<div class="bg"></div>
			<div class="section-inner">

				<div class="container">

					<div class="intro">
						<header class="heading">
							<h1 class="wow zoomIn"><span class="name">Eu sou <span class="fn">Neuly Ferreira</span></span><span class="animated-letters category"><b class="is-visible">Gastronomia</b><b>Moda</b><b>Kids</b><b>Solidariedade</b><b>Cultural</b></span></h1>
							<div class="separator wow zoomIn"></div>
						</header>

						<div data-wow-delay="0.1s" class="wow fadeInUp"><a href="#about" class="btn btn-bordered btn-go">Conheça</a></div>
					</div>

				</div>

			</div>
			<canvas id="particles"></canvas>
		</section>
		<!-- END HEADER-->



		<%= yield %>

	



		<!-- BEGIN FOOTER-->
		<section id="contacts" class="section  section-bg-overlay section-top-rise" style="background:black">
			<div class="bg"></div>
			<div class="section-inner">

				<div class="container">

					<header class="heading">
						<h2>Contato</h2>
						<div class="separator"></div>
					</header>

					<div class="contacts">
						<div class="row">
							<div class="col span_4">
								<div class="contacts-item">
									<div class="icon-b"><i class="fa fa-map-marker"></i></div>
									<address class="adr"><span class="country-name">Coxim</span>, <span class="locality">Mato Grosso do Sul</span></address>
								</div>
							</div>
							<div class="col span_4">
								<div class="contacts-item">
									<div class="icon-b"><i class="fa fa-phone"></i></div><span class="tel">(67) 9907-2956</span>
								</div>
							</div>
							<div class="col span_4">
								<div class="contacts-item">
									<div class="icon-b"><i class="fa fa-send"></i></div><a href="mailto:mail@yoursite.com" class="email">neulyf.silva@gmail.com</a>
								</div>
							</div>
						</div>
					</div>
					

				</div>

			</div>
		</section>
		<!-- END FOOTER-->

	</div>

	<!-- jQuery-->
	<script src="/scripts/jquery.min.js"></script>

	<!-- Instafeed-->
	<script src="/plugins/instafeed/instafeed.min.js"></script>

	<!-- Google Maps API-->
	<script src="https://maps.googleapis.com/maps/api/js?v=3.exp"></script>

	<!-- Magnific Popup-->
	<script src="/plugins/magnific-popup/jquery.magnific-popup.min.js"></script>

	<!-- One Page Nav-->
	<script src="/plugins/one-page-nav/jquery.nav.js"></script>

	<!-- Owl Carousel-->
	<script src="/plugins/owl-carousel/owl.carousel.min.js"></script>

	<!-- Shuffle-->
	<script src="/plugins/shuffle/jquery.shuffle.modernizr.min.js"></script>

	<!-- Twitter Fetcher-->
	<script src="/plugins/twitter-fetcher/twitterFetcher_min.js"></script>

	<!-- Validate-->
	<script src="/plugins/jquery-validate/jquery.validate.min.js"></script>

	<!-- WOW-->
	<script src="/plugins/wowjs/wow.min.js"></script>

	<!-- Main Scripts-->
	<script src="/scripts/main.js"></script>

	<!-- Customizer-->
	<script src="/scripts/customizer.js"></script>

</body>

</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br>
    <%= f.text_field :category_id %>
  </div>
  <div class="field">
    <%= f.label :author_id %><br>
    <%= f.text_field :author_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Content</th>
      <th>Category</th>
      <th>Author</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.description %></td>
        <td><%= post.content %></td>
        <td><%= post.category %></td>
        <td><%= post.author %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<section class="section">
      <div class="section-inner">

        <div class="container">

          <header class="heading">
            <h2><%= @post.title %></h2>
          </header>

          <article class="post">

            <div class="post-meta">
              <div class="date"><%= @post.created_at.strftime('%d/%m/%Y') %></div>
            </div>

            <div class="post-thumbnail"><img src="<%= @post.cover %>" width="940" height="752" alt=""></div>

              <p>
                
                <%= @post.description %>
              </p>
<blockquote>
<p>
  
  <%= @post.content %>
</p>
</blockquote>
<div class="row">
              <div class="col span_6">
                <ul>
                  <li><%= @post.category.name %></li>
                  
                </ul>
              </div>


<p>
  
  Por, <%= @post.author.name %>
</p>

  </div>
      </div>
    </section>